<?php

namespace Ht7\Tests\Base;

use \BadMethodCallException;
use PHPUnit\Framework\TestCase;
use Ht7\Base\Ht7Object;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-12-01 at 20:41:17.
 */
class Ht7ObjectTest extends TestCase
{

    /**
     * @var Ht7\Base\Ht7Object
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Ht7Object;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Ht7\Base\Ht7Object::__call
     * @dataProvider callProvider
     */
    public function test__call($name, $args) {
        $this->expectException(BadMethodCallException::class);

        $this->object->$name($args);
    }

    public function callProvider() {
        return [
            ['getName', ''],
            ['setName', 'test01'],
            ['getTest', ''],
            ['setTest', 'test02']
        ];
    }

}
